// ===== v0.4.0 药品库(48 → 52 款)=====
//
// 任务来源:实施员 3 · 药品库扩容 + 推广标记
// 实施日期:2026-08-04
// 实施依据:
//   - plan.md §2.5 F-MED-01(48 款 / 11 分类 / Free 也能看 / 完整字段)
//   - plan.md §2.5 F-MED-02(推广药品置顶 + 黄色「推广」角标)
//   - implementation.md §3 #15 #16(medicine/page.tsx 排序 + ClientView 角标)
//   - rectification-report.md(8 个 MUST 拍板)
//
// 数量说明:任务清单列了 8+6+6+6+4+4+4+4+4+4+2 = **52** 款真实药品名
//   (头注"10→48"是 plan 早期口径,后增到 52 款;以清单为准)
//   推广药 = **4 款**(3-5 区间;驱虫 2 + 疫苗 1 + 肠胃 1,**不**全标)
//
// 字段要求(任务清单):
//   - `indications[]` 适应症条目(详情页 chip 化展示)
//   - `dosage` 剂量(原字段沿用,文案统一)
//   - `contraindications` 禁忌(原 plan 字段 `notice` 改名,UI 文案统一)
//   - `description` 50-100 字说明(原 10 字左右太短;v0.4.0 详情页主展示)
//
// 推广策略(任务清单):
//   - 4 款标 isPromoted=true(驱虫 2 + 疫苗 1 + 肠胃 1;**不**全标)
//   - 推广药在搜索结果**排前**但不**伪装**(明确标"推广"红色徽章)
//   - promotedRank 越大越靠前
//   - getPromotedDrugs() 工具函数返回推广药(在 sponsored.ts)
//
// 设计取舍:
//   - `category` 保留老 "营养" / "眼耳口" 以兼容旧 drugs 数组(虽然这里全是新类)
//   - `symptoms` 仍填 3-5 个关键词(给 medicine/page.tsx 现有搜索 + 症状快捷入口复用)
//   - 处方药标 `prescription: true`(任务清单的"处方药标记"沿用旧字段)
//   - 不藏药:Free 用户也能看到全部 52 款;vipOnly=true 的药 Free 模糊(沿用旧行为)
//
// 适配动物 (PetSpecies) 候选:"cat" | "dog" | "rabbit" | "bird" | "other"
//   - 绝大多数猫狗通用;少数仅猫/仅犬;心脏/肾脏药多猫狗通用

import type { Drug } from "../types";

// ===== 驱虫(8 款)=====
const deworming: Drug[] = [
  {
    id: "drug_deworm_01",
    name: "福来恩滴剂",
    category: "驱虫",
    symptoms: ["体外驱虫", "跳蚤", "蜱虫", "虱子"],
    description: "法国梅里亚出品,非泼罗尼成分外用滴剂。跳蚤 24h 内起效,蜱虫 48h 起效,效力持续一个月。拨开颈后毛发滴于皮肤即可,使用前后 48h 避免洗澡。",
    indications: ["跳蚤感染", "蜱虫感染", "虱子", "体外寄生虫预防"],
    dosage: "按体重选规格(小型 / 中型 / 大型),拨开颈后毛发,滴于皮肤 3-4 个点。每月 1 次。",
    sideEffects: "偶见用药部位局部皮肤发红;极少出现流涎或精神不振(舔舐后)。",
    contraindications: "8 周龄以下幼犬/幼猫禁用;体重 1kg 以下禁用;用药部位皮肤破损禁用。",
    price: 78,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_deworm_02",
    name: "拜耳拜宠清(Drontal)",
    category: "驱虫",
    symptoms: ["体内驱虫", "蛔虫", "绦虫", "钩虫", "鞭虫"],
    description: "德国拜耳出品,非处方广谱体内驱虫药。覆盖蛔虫、绦虫、钩虫、鞭虫四大常见肠道寄生虫。味甜,直接喂食或包入零食,犬猫接受度高。",
    indications: ["蛔虫", "绦虫", "钩虫", "鞭虫", "肠道寄生虫预防"],
    dosage: "犬:1 片 / 10kg 体重;猫:1/4-1/2 片 / 4kg 体重。每 3 月 1 次。",
    sideEffects: "偶见轻微呕吐、软便,通常 24h 内自行缓解。",
    contraindications: "怀孕初期(配种后 25 天内)慎用;2 周龄以下幼猫/幼犬禁用;体重过轻(<1kg)禁用。",
    price: 45,
    prescription: false,
    forSpecies: ["cat", "dog"],
    isPromoted: true,
    promotedRank: 90,
  },
  {
    id: "drug_deworm_03",
    name: "大宠爱(Revolution / 塞拉菌素)",
    category: "驱虫",
    symptoms: ["内外同驱", "心丝虫", "跳蚤", "耳螨", "疥螨"],
    description: "美国辉瑞(现 Zoetis)出品,塞拉菌素外用滴剂。一支覆盖体内外 6 大常见寄生虫:跳蚤、耳螨、疥螨、虱子、心丝虫预防、肠道钩虫。",
    indications: ["心丝虫预防", "跳蚤", "耳螨", "疥螨", "虱子", "肠道钩虫"],
    dosage: "按体重选规格,滴于颈后皮肤。每月 1 次。心丝虫预防需全年每月连续使用。",
    sideEffects: "极少见;用药部位可能短暂油腻或毛发粘连。",
    contraindications: "8 周龄以下幼犬/幼猫禁用;犬恶丝虫成虫阳性(D. immitis)禁用(会引起严重反应)。",
    price: 168,
    prescription: false,
    forSpecies: ["cat", "dog"],
    isPromoted: true,
    promotedRank: 95,
  },
  {
    id: "drug_deworm_04",
    name: "爱沃克(Advocate / 吡虫啉莫昔克丁)",
    category: "驱虫",
    symptoms: ["内外同驱", "心丝虫", "跳蚤", "螨虫", "胃肠道线虫"],
    description: "德国拜耳出品,吡虫啉+莫昔克丁复方滴剂。覆盖心丝虫预防、跳蚤、疥螨、耳螨及胃肠道线虫(蛔虫/钩虫/鞭虫)。适用于 7 周龄以上犬猫。",
    indications: ["心丝虫预防", "跳蚤", "耳螨", "疥螨", "胃肠道线虫"],
    dosage: "按体重选规格,滴于颈后皮肤 3-4 个点。每月 1 次。",
    sideEffects: "偶见用药部位皮肤刺激、瘙痒,大型犬可能短暂嗜睡。",
    contraindications: "7 周龄以下或体重 1kg 以下禁用;已知莫昔克丁过敏禁用。",
    price: 158,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_deworm_05",
    name: "心疥爽(Interceptor / 米尔贝肟)",
    category: "驱虫",
    symptoms: ["心丝虫", "蛔虫", "钩虫", "鞭虫", "犬专用"],
    description: "美国礼来(现 Elanco)出品,米尔贝肟成分口服片。犬专用,主攻心丝虫预防及胃肠道线虫(蛔虫/钩虫/鞭虫),每月 1 次口服。",
    indications: ["心丝虫预防", "蛔虫", "钩虫", "鞭虫"],
    dosage: "按体重选规格(2.3-25kg+),每月 1 次口服,可拌入食物。",
    sideEffects: "罕见;个别犬出现呕吐、嗜睡,多在 24h 内缓解。",
    contraindications: "已确诊心丝虫成虫阳性禁用(需先治疗);6 周龄以下或体重 2 磅以下禁用。",
    price: 88,
    prescription: false,
    forSpecies: ["dog"],
  },
  {
    id: "drug_deworm_06",
    name: "犬心保(Heartgard / 伊维菌素)",
    category: "驱虫",
    symptoms: ["心丝虫", "犬专用", "每月口服"],
    description: "美国梅里亚(现勃林格)出品,伊维菌素+双氢睾酮复方咀嚼片。犬专用,主防心丝虫及钩虫/蛔虫,牛肉味接受度高,每月 1 次。",
    indications: ["心丝虫预防", "蛔虫", "钩虫"],
    dosage: "按体重选规格(犬专用 0-11kg / 12-22kg / 23-45kg),每月 1 次口服,全年连续使用。",
    sideEffects: "罕见;个别犬(尤其柯利系牧羊犬)对伊维菌素敏感需慎用,大剂量出现神经症状。",
    contraindications: "已确诊心丝虫成虫阳性禁用;柯利犬/喜乐蒂等 MDR1 突变犬种慎用(选替代药);6 周龄以下禁用。",
    price: 98,
    prescription: false,
    forSpecies: ["dog"],
  },
  {
    id: "drug_deworm_07",
    name: "妙巴(Milbemax / 米尔贝肟+吡喹酮)",
    category: "驱虫",
    symptoms: ["心丝虫", "绦虫", "蛔虫", "钩虫", "猫犬通用"],
    description: "瑞士诺华(现 Elanco)出品,米尔贝肟+吡喹酮复方口服片。猫犬通用,覆盖心丝虫预防、绦虫、蛔虫、钩虫,每 3 月 1 次广谱驱虫。",
    indications: ["心丝虫预防", "绦虫", "蛔虫", "钩虫"],
    dosage: "按体重选规格,口服,可直接喂或拌入食物。6 周龄以上每 3 月 1 次;心丝虫预防需每月 1 次。",
    sideEffects: "罕见;偶见短暂嗜睡、呕吐。",
    contraindications: "6 周龄以下或体重 0.5kg 以下禁用;已知米尔贝肟/吡喹酮过敏禁用。",
    price: 65,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_deworm_08",
    name: "拜耳内虫逃(Drontal Plus)",
    category: "驱虫",
    symptoms: ["体内驱虫", "广谱", "猫用", "犬用"],
    description: "德国拜耳出品,吡喹酮+噻嘧啶+奥芬达唑三联复方。广谱体内驱虫,覆盖 12 种以上常见肠道寄生虫,效果强于单方拜宠清。",
    indications: ["蛔虫", "绦虫", "钩虫", "鞭虫", "肠道混合感染"],
    dosage: "按体重选规格,直接口服或拌入食物。每 3 月 1 次,高感染风险环境每月 1 次。",
    sideEffects: "偶见呕吐、软便;罕见流涎。",
    contraindications: "怀孕初期禁用;3 周龄以下幼猫/幼犬禁用;严重肝肾功能不全禁用。",
    price: 75,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
];

// ===== 疫苗(6 款)=====
const vaccines: Drug[] = [
  {
    id: "drug_vaccine_01",
    name: "妙三多(Felocell CVR / 猫三联)",
    category: "疫苗",
    symptoms: ["猫瘟", "猫鼻支", "猫杯状", "猫三联"],
    description: "美国辉瑞(现 Zoetis)出品,猫咪核心三联疫苗。预防猫泛白细胞减少症(猫瘟)、猫疱疹病毒(猫鼻支)、猫杯状病毒三大致命传染病,8 周龄起首免。",
    indications: ["猫瘟(泛白细胞减少症)", "猫疱疹病毒(猫鼻支)", "猫杯状病毒"],
    dosage: "8 周龄首免,每隔 4 周加强 1 次,共 3 针。首年免疫后每年加强 1 针,皮下注射。",
    sideEffects: "接种后 24h 可能精神不佳、低热,1-2 天自愈。偶见注射部位肿胀。",
    contraindications: "发烧、患病、怀孕猫禁用;免疫抑制治疗期禁用;与上次疫苗间隔不足 2 周禁用。",
    price: 120,
    prescription: true,
    forSpecies: ["cat"],
    isPromoted: true,
    promotedRank: 100,
  },
  {
    id: "drug_vaccine_02",
    name: "卫佳捌(Vanguard Plus 5/CV)",
    category: "疫苗",
    symptoms: ["犬瘟", "犬细小", "犬腺病毒", "犬副流感", "犬钩端螺旋体"],
    description: "美国辉瑞(现 Zoetis)出品,犬用八联疫苗。覆盖犬瘟热、犬细小、腺病毒 1 型(传染性肝炎)与 2 型(呼吸道病)、犬副流感、4 型钩端螺旋体共 8 种疾病。",
    indications: ["犬瘟热", "犬细小病毒", "犬腺病毒(肝炎+呼吸道)", "犬副流感", "钩端螺旋体病"],
    dosage: "6 周龄首免,每隔 2-3 周加强 1 次,共 4 针。首年免疫后每年加强 1 针,皮下注射。",
    sideEffects: "接种后 1-2 天可能精神不振、低热、食欲下降;偶见注射部位肿胀(1-2 周吸收)。",
    contraindications: "发烧、患病、怀孕母犬禁用;免疫抑制治疗期禁用;上次疫苗过敏史禁用。",
    price: 180,
    prescription: true,
    forSpecies: ["dog"],
  },
  {
    id: "drug_vaccine_03",
    name: "狂犬疫苗(Rabies)",
    category: "疫苗",
    symptoms: ["狂犬病", "法定免疫"],
    description: "国内外多家厂商生产(国产 / 进口如 Nobivac Rabies),犬猫法定免疫疫苗。注射后国家认可,办理犬证必打,保护期 1 年或 3 年(看产品)。",
    indications: ["狂犬病(预防)"],
    dosage: "3 月龄以上首免,1 针皮下或肌肉注射;之后每年(或每 3 年)加强 1 针。",
    sideEffects: "罕见;偶见注射部位疼痛、低热。",
    contraindications: "发烧、患病、怀孕动物禁用;上次狂犬疫苗严重过敏禁用;6 周龄以下禁用。",
    price: 60,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_vaccine_04",
    name: "英特威(Nobivac / 荷兰英特威)",
    category: "疫苗",
    symptoms: ["犬瘟", "犬细小", "猫三联", "进口疫苗"],
    description: "荷兰默沙东(MSD)出品,犬猫通用多联疫苗系列。包括 Nobivac DHPPi(犬四联)、Nobivac Tricat(猫三联)等,进口高端疫苗。",
    indications: ["犬瘟热", "犬细小病毒", "犬腺病毒", "犬副流感", "猫瘟", "猫鼻支", "猫杯状"],
    dosage: "按系列选剂型;犬 6 周龄首免、猫 8 周龄首免,每隔 3-4 周加强 1 次,共 3 针。皮下注射。",
    sideEffects: "接种后短暂精神不佳、低热;偶见注射部位肿块。",
    contraindications: "发烧、患病、怀孕动物禁用;免疫抑制期禁用;已知疫苗成分过敏禁用。",
    price: 95,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_vaccine_05",
    name: "辉瑞卫佳五(Vanguard Plus 5)",
    category: "疫苗",
    symptoms: ["犬瘟", "犬细小", "犬腺病毒", "犬副流感"],
    description: "美国辉瑞(现 Zoetis)出品,犬用五联疫苗,基础核心疫苗。覆盖犬瘟热、犬细小、犬腺病毒(2 型)、犬副流感,适合 6-8 周龄幼犬首免。",
    indications: ["犬瘟热", "犬细小病毒", "犬腺病毒(呼吸道)", "犬副流感"],
    dosage: "6 周龄首免,每隔 2-3 周加强 1 次,共 4 针。首年后每年加强 1 针,皮下注射。",
    sideEffects: "偶见低热、精神不佳(1-2 天自愈);罕见过敏反应(颜面水肿、呼吸困难)。",
    contraindications: "发烧、患病、怀孕犬禁用;上次同类疫苗过敏禁用。",
    price: 130,
    prescription: true,
    forSpecies: ["dog"],
  },
  {
    id: "drug_vaccine_06",
    name: "瑞贝康(Rabigen / SAG2 口服狂犬)",
    category: "疫苗",
    symptoms: ["狂犬病", "口服疫苗", "野生动物"],
    description: "法国 Virbac 出品,口服狂犬病疫苗(SAG2 减毒株),主要用于野生动物(狐狸、浣熊)口服免疫投放。宠物临床少用,但作为行业参考列出。",
    indications: ["狂犬病(野生动物群体免疫)"],
    dosage: "由专业人员投放至诱饵中,野生动物经口摄入。宠物不可家用。",
    sideEffects: "减毒株残留毒性极低;但严禁宠物口服(未经批准)。",
    contraindications: "仅限野生动物投放;家养宠物不可用;怀孕动物禁用。",
    price: 0,    // 不零售
    prescription: true,
    forSpecies: ["other"],
  },
];

// ===== 肠胃(6 款)=====
const digestive: Drug[] = [
  {
    id: "drug_digestive_01",
    name: "宠物益生菌粉(FortiFlora)",
    category: "肠胃",
    symptoms: ["腹泻", "软便", "换粮", "便秘", "食欲不振"],
    description: "美国默沙东(MSD)出品,宠物专用益生菌补充剂,含布拉迪酵母菌(Saccharomyces boulardii)。改善肠道菌群,适用于腹泻/软便/换粮过渡期/抗生素后调理。",
    indications: ["急性腹泻", "慢性软便", "换粮过渡", "抗生素后菌群失调", "食欲不振"],
    dosage: "每日 1 袋,拌入食物或温水(<40℃)冲服。可长期使用;急性期连用 7-14 天。",
    sideEffects: "基本无副作用;免疫缺陷宠物(如化疗中)咨询医生。",
    contraindications: "已知酵母菌过敏禁用;免疫严重抑制个体禁用;需配合抗生素时错开 2h 服用。",
    price: 25,
    prescription: false,
    forSpecies: ["cat", "dog"],
    isPromoted: true,
    promotedRank: 80,
  },
  {
    id: "drug_digestive_02",
    name: "蒙脱石散(思密达通用名)",
    category: "肠胃",
    symptoms: ["急性腹泻", "水样便", "吸附止泻"],
    description: "法国博福-益普生出品(原研),双八面体蒙脱石散,胃肠黏膜保护剂。吸附病原体和毒素,保护肠黏膜,适用于急性水样腹泻。宠物用儿童规格减量。",
    indications: ["急性水样腹泻", "病毒性腹泻辅助", "食物中毒辅助"],
    dosage: "犬:1-2 袋/次(3g/袋),每日 2-3 次;猫:1/3-1/2 袋/次,每日 2-3 次。用温水冲服,与其他药/食物错开 2h。",
    sideEffects: "偶见便秘(过量);长期使用可能影响其他药物吸收。",
    contraindications: "严重脱水伴电解质紊乱时禁用(需先补液);已知蒙脱石过敏禁用;与抗菌药/益生菌同服需错开 2h。",
    price: 18,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_digestive_03",
    name: "思密达(Smecta / 草莓味)",
    category: "肠胃",
    symptoms: ["腹泻", "肠黏膜保护", "儿童规格"],
    description: "法国博福-益普生原研,蒙脱石散草莓味制剂,与通用名「蒙脱石散」成分相同。宠物临床常买儿童规格减量使用,适口性更好。",
    indications: ["急性腹泻", "肠黏膜修复", "病毒性肠炎辅助"],
    dosage: "同蒙脱石散。草莓味可直接兑少量水用注射器灌服,猫接受度更高。",
    sideEffects: "同蒙脱石散;偶见轻度便秘。",
    contraindications: "同蒙脱石散;同其他药物错开 2h 服用。",
    price: 22,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_digestive_04",
    name: "胃溃宁(Sucralfate / 硫糖铝片)",
    category: "肠胃",
    symptoms: ["胃溃疡", "胃黏膜保护", "胃酸过多"],
    description: "胃黏膜保护剂,在酸性环境下形成保护膜覆盖溃疡面,促进愈合。适用于胃溃疡、十二指肠溃疡、胃炎伴黏膜糜烂。宠物用人药规格减量。",
    indications: ["胃溃疡", "十二指肠溃疡", "急性胃炎", "胃黏膜糜烂", "NSAIDs 引起的胃损伤"],
    dosage: "犬:0.5-1g/次,每日 2-3 次;猫:0.25-0.5g/次,每日 2-3 次。空腹(餐前 1h 或餐后 2h)口服。",
    sideEffects: "偶见便秘、口干;长期使用可能影响维生素吸收。",
    contraindications: "严重肾功能障碍禁用(铝蓄积);与抗酸药、H2 受体拮抗剂同服需错开 30 分钟。",
    price: 28,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_digestive_05",
    name: "硫糖铝(原料药 / 兽用混悬液)",
    category: "肠胃",
    symptoms: ["胃溃疡", "胃黏膜保护", "兽用剂型"],
    description: "硫糖铝兽用混悬液剂型,适合小型犬猫精确给药,优于片剂分装。在酸性胃液中形成胶体保护溃疡面,促进黏膜再生。",
    indications: ["胃溃疡", "急性胃炎", "慢性胃炎", "药物性胃损伤"],
    dosage: "按体重 0.25-1g/次,每日 2-4 次,空腹口服(餐前 1h)。混悬液直接用注射器灌服。",
    sideEffects: "偶见便秘;长期使用注意低磷血症。",
    contraindications: "严重肾功能障碍禁用;怀孕动物安全性未完全确立,慎用。",
    price: 35,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_digestive_06",
    name: "胃复安(Metoclopramide / 甲氧氯普胺)",
    category: "肠胃",
    symptoms: ["呕吐", "胃动力", "止吐"],
    description: "胃动力促进剂 + 中枢止吐药,通过阻断多巴胺 D2 受体起作用。适用于胃肠动力不足引起的恶心、呕吐(如胃瘫、化疗后呕吐、尿毒症呕吐)。",
    indications: ["胃肠动力不足", "胃瘫", "化疗后呕吐", "尿毒症呕吐", "术后呕吐"],
    dosage: "犬:0.2-0.5 mg/kg,每日 3-4 次,餐前 30 分钟口服或皮下注射;猫:0.2-0.4 mg/kg,每日 3-4 次。",
    sideEffects: "常见嗜睡;偶见兴奋不安、震颤(尤其猫);长期使用可能引起锥体外系症状。",
    contraindications: "胃肠道机械性梗阻/穿孔禁用;癫痫病史禁用;嗜铬细胞瘤禁用;怀孕早期禁用。",
    price: 15,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
];

// ===== 皮肤(6 款)=====
const skin: Drug[] = [
  {
    id: "drug_skin_01",
    name: "皮炎平(复方醋酸地塞米松软膏)",
    category: "皮肤",
    symptoms: ["皮炎", "湿疹", "过敏瘙痒", "局部消炎"],
    description: "人用非处方外用糖皮质激素软膏,宠物可小面积短期使用。含醋酸地塞米松+樟脑+薄荷脑,消炎止痒,适用于急性湿疹、过敏性皮炎局部。",
    indications: ["急性湿疹", "过敏性皮炎", "局部瘙痒", "虫咬皮炎"],
    dosage: "涂薄层于患处,每日 2 次,连用不超过 7 天。破损皮肤禁用,避免舔舐(配合伊丽莎白圈)。",
    sideEffects: "长期使用引起皮肤萎缩、色素沉着;大面积使用可能全身吸收致肾上腺抑制。",
    contraindications: "皮肤破损/感染禁用;面部、腋下、腹股沟薄皮肤慎用;猫对糖皮质激素敏感,慎用。",
    price: 8,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_skin_02",
    name: "可鲁(复方氯己定含漱液 / 外用)",
    category: "皮肤",
    symptoms: ["细菌性皮炎", "创面消毒", "脓皮症"],
    description: "国产宠物医院常用消毒剂,主要成分醋酸氯己定。广谱杀菌,对革兰氏阳性/阴性菌均有效,刺激性低,适用于浅表脓皮症、创面清洁、术前消毒。",
    indications: ["浅表脓皮症", "创面清洁", "术前消毒", "趾间炎", "擦伤"],
    dosage: "冲洗或湿敷患处,每日 1-2 次,连用 7-14 天。可稀释 1:10 用于大面积清洗。",
    sideEffects: "极少见;偶见接触性皮炎。",
    contraindications: "对氯己定过敏禁用;耳道内禁用(中耳风险);避免与肥皂/阴离子表面活性剂合用。",
    price: 45,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_skin_03",
    name: "麦高臣(Malacetic / 耳肤灵同厂)",
    category: "皮肤",
    symptoms: ["外耳炎", "耳螨", "马拉色菌", "皮肤褶皱炎"],
    description: "美国 Dechra 出品,醋酸+硼酸复方外用制剂。适用于马拉色菌性外耳炎、皮肤褶皱炎、趾间炎,广谱抗真菌+弱抑菌。",
    indications: ["马拉色菌性外耳炎", "皮肤褶皱炎", "趾间炎", "脂溢性皮炎"],
    dosage: "外耳道:滴入数滴,轻揉 30 秒,每日 1 次。皮肤:涂患处每日 1-2 次,连用 7-14 天。",
    sideEffects: "偶见用药部位刺激;罕见局部过敏反应。",
    contraindications: "鼓膜穿孔禁用;对醋酸/硼酸过敏禁用;避免入眼。",
    price: 85,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_skin_04",
    name: "维克耳肤灵(Virbac Epi-Otic / 耳漂同厂)",
    category: "皮肤",
    symptoms: ["耳道清洁", "耳螨辅助", "日常护理"],
    description: "法国 Virbac 出品,耳道清洁液。温和表面活性剂+保湿剂,日常清洁耳道、溶解耳垢、辅助治疗耳螨/外耳炎。宠物医院主流品牌。",
    indications: ["耳道日常清洁", "耳螨治疗辅助", "外耳炎辅助", "游泳后清洁"],
    dosage: "滴入耳道,轻揉 30 秒,让宠物甩出,棉球擦干外耳。每日 1 次(治疗期)或每周 1-2 次(日常)。",
    sideEffects: "极少见;偶见耳道短暂刺激。",
    contraindications: "鼓膜穿孔禁用;急性感染期需配合抗生素,不能单用;入眼立即冲洗。",
    price: 95,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_skin_05",
    name: "皮康王(复方酮康唑软膏)",
    category: "皮肤",
    symptoms: ["真菌", "皮癣", "体癣", "抗真菌"],
    description: "复方酮康唑+氯倍他索软膏,广谱抗真菌+糖皮质激素复方制剂。适用于真菌性皮癣、念珠菌性皮炎、脂溢性皮炎,止痒消炎同步。",
    indications: ["体癣", "股癣", "手足癣", "脂溢性皮炎", "念珠菌性皮炎"],
    dosage: "涂薄层于患处,每日 2 次,连用 2-4 周。症状消失后继续用 1 周防复发。",
    sideEffects: "长期使用致皮肤萎缩、毛细血管扩张;偶见接触性皮炎。",
    contraindications: "面部、腋下、腹股沟薄皮肤慎用;皮肤破损/感染禁用;猫慎用(糖皮质激素敏感);怀孕动物禁用。",
    price: 12,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_skin_06",
    name: "酮康唑(Ketoconazole / 口服抗真菌)",
    category: "皮肤",
    symptoms: ["全身真菌", "念珠菌", "球孢子菌", "马拉色菌"],
    description: "广谱唑类抗真菌药,口服用于治疗全身性真菌感染(球孢子菌病、念珠菌病、马拉色菌性皮炎等)。肝脏负担较大,需医生指导下使用。",
    indications: ["球孢子菌病", "组织胞浆菌病", "念珠菌病", "马拉色菌性皮炎(严重)", "皮肤真菌"],
    dosage: "犬:5-10 mg/kg,每日 1 次,餐时口服;猫:5-10 mg/kg,每日 1 次(耐受性较差,需监测肝功)。",
    sideEffects: "常见:呕吐、食欲不振;严重:肝毒性(尤其猫)、肾上腺抑制、男性化(长期高剂量)。",
    contraindications: "严重肝功能不全禁用;怀孕动物禁用(致畸);与多种药物相互作用(如西咪替丁、抗酸剂),需告知医生。",
    price: 38,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
];

// ===== 关节(4 款)=====
const joint: Drug[] = [
  {
    id: "drug_joint_01",
    name: "萨沙关节灵(Sasha's Joint Formula)",
    category: "关节",
    symptoms: ["关节", "髋关节", "老年犬", "绿唇贻贝"],
    description: "澳洲进口关节保健品,主要成分绿唇贻贝(GLM)提取物,富含 omega-3 脂肪酸和糖胺聚糖。适用于老年犬猫关节保养、髋关节发育不良辅助。",
    indications: ["髋关节发育不良(CHD)", "骨关节炎", "老年关节退化", "术后关节恢复"],
    dosage: "犬(按体重):<15kg 1 粒/日,15-30kg 2 粒/日,>30kg 3 粒/日;猫:1 粒/日。随餐服用。",
    sideEffects: "罕见;偶见轻微胃肠不适,随餐服用可缓解。",
    contraindications: "对贝类海鲜过敏禁用;抗凝药治疗期慎用(GLM 有轻度抗凝作用);术前 2 周停用。",
    price: 198,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_joint_02",
    name: "Cosequin(关节宝 / 葡萄糖胺+软骨素)",
    category: "关节",
    symptoms: ["关节", "髋关节", "老年犬", "中大型犬"],
    description: "美国 Nutramax 出品,盐酸葡萄糖胺+硫酸软骨素+MSM 三联关节保健。宠物骨关节炎一线保健品,适合中大型犬和老年犬。",
    indications: ["犬骨关节炎", "髋关节发育不良", "椎间盘疾病辅助", "术后关节恢复", "老年关节保养"],
    dosage: "初期 4-6 周:加倍剂量(犬 2-4 粒/日);维持期:1-2 粒/日;猫:1 粒/日。随餐服用。",
    sideEffects: "罕见;偶见轻度软便,建议随餐服用。",
    contraindications: "对贝类(葡萄糖胺来源)过敏禁用;糖尿病宠物咨询医生(可能影响血糖);抗凝药治疗期慎用。",
    price: 158,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_joint_03",
    name: "麦德氏(MedLab / 鲨鱼软骨素)",
    category: "关节",
    symptoms: ["关节", "鲨鱼软骨", "中老年犬", "关节营养"],
    description: "国产高端关节保健品,主要成分鲨鱼软骨素+葡萄糖胺。适合中老年犬关节保养,适口性好,可拌入主粮。",
    indications: ["犬骨关节炎", "关节疼痛", "中老年关节退化", "运动量大的工作犬"],
    dosage: "小型犬(<10kg):1 粒/日;中型犬(10-25kg):2 粒/日;大型犬(>25kg):3 粒/日。随餐或零食喂食。",
    sideEffects: "罕见;偶见轻度胃肠不适。",
    contraindications: "对鲨鱼/鱼类过敏禁用;抗凝药治疗期慎用;术前 2 周停用。",
    price: 128,
    prescription: false,
    forSpecies: ["dog"],
  },
  {
    id: "drug_joint_04",
    name: "关节生(Joint Genesis / UC-II)",
    category: "关节",
    symptoms: ["关节", "UC-II", "软骨修复", "新型保健品"],
    description: "美国新型关节保健品,专利成分 UC-II(非变性 II 型胶原蛋白)40mg/日,临床证实可调节免疫、减缓关节软骨破坏。适合早期骨关节炎和预防性保养。",
    indications: ["早期骨关节炎", "关节软骨保护", "免疫调节", "中大型犬髋关节保养"],
    dosage: "犬:1 粒/日(<40kg),2 粒/日(>40kg);猫:1/2-1 粒/日。空腹或餐前服用效果更佳。",
    sideEffects: "罕见;偶见轻度腹泻。",
    contraindications: "对蛋类/鸡肉来源成分过敏禁用;免疫抑制治疗期禁用(可能影响药效);怀孕动物安全性未确立。",
    price: 168,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
];

// ===== 心脏(4 款)=====
const heart: Drug[] = [
  {
    id: "drug_heart_01",
    name: "匹莫苯丹(Pimobendan / Vetmedin)",
    category: "心脏",
    symptoms: ["心衰", "心脏增大", "CHF", "强心"],
    description: "德国勃林格出品,宠物心衰一线用药。钙离子增敏剂+磷酸二酯酶 3 抑制剂双重机制,增强心肌收缩力+扩张血管,显著延长瓣膜性 CHF 患犬生存期。",
    indications: ["犬瓣膜性 CHF(左心衰为主)", "扩张型心肌病(DCM)", "心脏增大无症状期(延长发病)"],
    dosage: "犬:0.25-0.3 mg/kg,每日 2 次,餐前 1h 口服;猫:1.25 mg/猫,每日 2 次(off-label,小剂量起步)。",
    sideEffects: "罕见;偶见食欲不振、轻度心率上升;严重过量可致心肌缺血。",
    contraindications: "肥厚型心肌病(HCM)禁用(增强收缩反而加重梗阻);主动脉狭窄禁用;急性心肌梗死禁用。",
    price: 380,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_heart_02",
    name: "呋塞米(Furosemide / 速尿)",
    category: "心脏",
    symptoms: ["利尿", "肺水肿", "腹水", "心衰"],
    description: "强效袢利尿剂,心衰/肺水肿/腹水一线用药。通过抑制钠钾氯共转运体强力利尿,迅速缓解充血性心衰症状。常与匹莫苯丹、ACEI 联合。",
    indications: ["充血性心衰(CHF)", "肺水肿", "腹水", "胸腔积液", "严重水肿"],
    dosage: "犬:1-4 mg/kg,每 8-12h 口服或静脉(急性);猫:1-2 mg/kg,每 8-12h 口服。重症可静脉注射。",
    sideEffects: "常见:多尿、电解质紊乱(低钾低钠);长期:脱水、肾前性氮质血症、耳毒性(大剂量静脉)。",
    contraindications: "无尿症禁用;严重电解质紊乱禁用;对磺胺类过敏禁用(部分动物);怀孕动物慎用。",
    price: 25,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_heart_03",
    name: "螺内酯(Spironolactone / 安体舒通)",
    category: "心脏",
    symptoms: ["保钾利尿", "心衰辅助", "醛固酮拮抗"],
    description: "保钾利尿剂,醛固酮拮抗剂。利尿作用弱但能阻断醛固酮介导的心肌/血管纤维化,作为 CHF 辅助用药可显著降低死亡率。常与呋塞米+ACEI 联用。",
    indications: ["CHF 长期辅助", "腹水(肝硬化/心源性)", "原发性醛固酮增多症"],
    dosage: "犬:1-2 mg/kg,每日 1-2 次口服;猫:1-2 mg/kg,每日 1-2 次。可单独或与呋塞米合用。",
    sideEffects: "常见:多饮多尿;罕见:高钾血症(尤其与 ACEI 合用)、消化道反应、男性化(长期)。",
    contraindications: "高钾血症禁用;严重肾功能不全禁用;无尿症禁用;怀孕动物禁用。",
    price: 18,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_heart_04",
    name: "贝那普利(Benazepril / 洛汀新)",
    category: "心脏",
    symptoms: ["ACEI", "降压", "心衰", "肾保护"],
    description: "血管紧张素转化酶抑制剂(ACEI),降压+减轻心脏后负荷+肾保护。适用于 CHF 长期管理、高血压、慢性肾病蛋白尿(尤其猫)。宠物心血管一线用药。",
    indications: ["犬 CHF 长期管理", "高血压", "猫慢性肾病(蛋白尿)", "心脏瓣膜病辅助"],
    dosage: "犬:0.25-0.5 mg/kg,每日 1 次口服;猫:0.5-1 mg/kg,每日 1 次口服。可单独或与利尿剂合用。",
    sideEffects: "常见:轻度低血压、嗜睡;罕见:高钾血症、急性肾损伤(尤其脱水时)、咳嗽(罕见于犬)。",
    contraindications: "怀孕动物禁用(致畸);急性肾损伤禁用;高钾血症禁用;与 NSAIDs 合用增加肾损伤风险。",
    price: 45,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
];

// ===== 肾脏(4 款)=====
const kidney: Drug[] = [
  {
    id: "drug_kidney_01",
    name: "肾衰停(Azodyl / 肠道氮吸附剂)",
    category: "肾脏",
    symptoms: ["慢性肾病", "氮质血症", "毒素吸附"],
    description: "美国 Vetoquinol 出品,宠物专用肾脏保健品,含特定益生菌(屎肠球菌+嗜酸乳杆菌+长双歧杆菌)可吸附肠道内尿毒素。配合肾病处方粮可显著降低 BUN/肌酐。",
    indications: ["IRIS 1-3 期慢性肾病(CKD)", "氮质血症辅助", "蛋白尿辅助"],
    dosage: "犬猫:<2.5kg 1 粒/日,2.5-4.5kg 2 粒/日,>4.5kg 3 粒/日。整粒吞服,不可咀嚼,餐时服用。",
    sideEffects: "极少见;偶见轻度软便。",
    contraindications: "急性肾损伤(AKI)无效;免疫抑制治疗期慎用(活菌);不可掰开/咀嚼(破坏包衣)。",
    price: 285,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_kidney_02",
    name: "胺肾(Aminoven / 复方氨基酸)",
    category: "肾脏",
    symptoms: ["慢性肾病", "必需氨基酸", "肾营养支持"],
    description: "复方氨基酸注射液/口服制剂,含肾病专用氨基酸谱(增加必需氨基酸,减少非必需氨基酸氮负荷)。适用于慢性肾病营养支持,常与低蛋白处方粮合用。",
    indications: ["慢性肾病营养支持", "尿毒症辅助", "低蛋白饮食氨基酸补充"],
    dosage: "按体重计算氨基酸需求,口服或输液。常用 0.5-1 g/kg/日,分 2-3 次。具体遵医嘱。",
    sideEffects: "静脉输注过快可致恶心、呕吐;罕见氨基酸失衡。",
    contraindications: "严重肝功能衰竭禁用(氨基酸代谢障碍);高氨血症禁用;对氨基酸过敏禁用。",
    price: 165,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_kidney_03",
    name: "开同(Ketosteril / 复方酮酸片)",
    category: "肾脏",
    symptoms: ["慢性肾病", "酮酸", "氮再利用"],
    description: "德国 Fresenius 出品,复方α-酮酸片。在体内转氨酶作用下与氮结合生成必需氨基酸,减少尿素氮生成,延缓 CKD 进展。配合极低蛋白饮食使用。",
    indications: ["CKD 3-4 期", "尿毒症前期", "低蛋白饮食氨基酸补充"],
    dosage: "犬:0.1-0.2 g/kg,每日 3 次餐时口服;猫:0.1 g/kg,每日 3 次餐时口服。不可空腹服用。",
    sideEffects: "罕见;偶见高钙血症(长期大剂量)。",
    contraindications: "高钙血症禁用;氨基酸代谢障碍禁用;需配合低蛋白饮食(否则无效)。",
    price: 220,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_kidney_04",
    name: "碳酸镧(Lanthanum Carbonate / 福斯利诺)",
    category: "肾脏",
    symptoms: ["高磷血症", "磷结合剂", "CKD"],
    description: "新型非钙磷结合剂,在肠道与磷酸根结合形成不溶性复合物排出,降低血磷且不增加钙负荷(优于传统钙剂)。适用于 CKD 高磷血症,尤其难控病例。",
    indications: ["CKD 高磷血症", "钙磷乘积升高", "传统磷结合剂无效/不耐受"],
    dosage: "犬:30-90 mg/kg/日,分 2-3 次餐时口服;猫:30-60 mg/kg/日,分 2-3 次餐时嚼碎服用。",
    sideEffects: "常见:恶心、便秘;罕见:低磷血症(过量)、肠道异物感(未嚼碎)。",
    contraindications: "低磷血症禁用;肠道梗阻禁用;对镧过敏禁用;必须餐时服用。",
    price: 198,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
];

// ===== 眼耳(4 款)=====
const eyeEar: Drug[] = [
  {
    id: "drug_eyeear_01",
    name: "耳漂(Virbac Epi-Otic Advanced)",
    category: "眼耳",
    symptoms: ["耳道清洁", "日常护理", "耳螨辅助"],
    description: "法国 Virbac 出品,耳道清洁液,宠物医院主流品牌。温和表面活性剂+水杨酸+保湿剂,溶解耳垢、维持耳道酸性环境,适用日常清洁和治疗期辅助。",
    indications: ["耳道日常清洁", "耳螨/外耳炎治疗辅助", "游泳后清洁", "拔毛前清洁"],
    dosage: "滴入耳道至液面可见,轻揉耳根 30 秒,让宠物甩出,棉球擦干外耳。治疗期每日 1 次,日常每周 1-2 次。",
    sideEffects: "极少见;偶见耳道短暂刺激(尤其破损时)。",
    contraindications: "鼓膜穿孔禁用;急性化脓性外耳炎需配合抗生素;入眼立即冲洗。",
    price: 95,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_eyeear_02",
    name: "耳肤灵(Otomax / 复方药膏)",
    category: "眼耳",
    symptoms: ["外耳炎", "耳螨", "细菌真菌混合"],
    description: "美国默沙东(MSD)出品,庆大霉素+倍他米松+克霉唑三联复方软膏。抗菌+抗真菌+消炎三效合一,适用于细菌/真菌/耳螨混合性外耳炎。",
    indications: ["细菌性外耳炎", "真菌性外耳炎(马拉色菌)", "耳螨感染", "混合感染"],
    dosage: "清洁耳道后,挤入豌豆大小药膏,轻揉耳根匀开。每日 1 次,连用 7-14 天。",
    sideEffects: "偶见耳道刺激;长期使用可能致耳道菌群失调;罕见全身吸收(糖皮质激素)。",
    contraindications: "鼓膜穿孔禁用;对氨基糖苷类/唑类/糖皮质激素过敏禁用;怀孕动物慎用;不可入眼。",
    price: 78,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_eyeear_03",
    name: "眼净(Optixcare / 宠物洗眼液)",
    category: "眼耳",
    symptoms: ["日常洗眼", "泪痕", "眼部分泌物"],
    description: "宠物专用洗眼液,温和无刺激,含透明质酸保湿。日常清洁眼部分泌物、泪痕,冲洗异物,术后/结膜炎辅助清洁。",
    indications: ["日常眼部清洁", "泪痕护理", "异物冲洗", "结膜炎辅助", "术后清洁"],
    dosage: "挤 2-3 滴于眼内,闭合眼睑轻揉 10 秒,自然流出或棉球擦干。每日 1-2 次或按需。",
    sideEffects: "极少见;偶见轻微短暂刺激。",
    contraindications: "深层角膜溃疡禁用(可能穿透);急性化脓性结膜炎需配合抗生素;入眼无刺激。",
    price: 65,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_eyeear_04",
    name: "辉瑞眼药(Tobramycin Ophthalmic / 妥布霉素滴眼液)",
    category: "眼耳",
    symptoms: ["结膜炎", "角膜炎", "细菌性眼疾"],
    description: "美国辉瑞(原研)出品,妥布霉素滴眼液,氨基糖苷类抗生素。适用于敏感菌引起的结膜炎、角膜炎、泪囊炎,起效快、刺激性低。",
    indications: ["细菌性结膜炎", "角膜炎", "泪囊炎", "术后眼部感染预防"],
    dosage: "患眼每次 1-2 滴,每 4-6h 1 次(急性期可加频至 2h 1 次)。疗程通常 5-7 天。",
    sideEffects: "偶见眼部短暂刺痛、视物模糊(滴入后 1-2 分钟);长期使用可能致真菌二重感染。",
    contraindications: "对氨基糖苷类过敏禁用;病毒性/真菌性结膜炎无效;不可长期使用(>14 天)。",
    price: 38,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
];

// ===== 抗感染(4 款)=====
const antiInfection: Drug[] = [
  {
    id: "drug_antiinf_01",
    name: "阿莫西林(Amoxicillin / 宠物用)",
    category: "抗感染",
    symptoms: ["细菌感染", "呼吸道", "泌尿道", "皮肤"],
    description: "广谱青霉素类抗生素,宠物临床一线用药。对革兰氏阳性和部分阴性菌有效,适用于呼吸道、泌尿道、皮肤软组织感染。**必须使用宠物规格,人药禁用(剂量/辅药不同)。**",
    indications: ["呼吸道感染", "泌尿道感染", "皮肤软组织感染", "术前预防"],
    dosage: "犬:10-20 mg/kg,每 8-12h 口服;猫:10-20 mg/kg,每 8-12h 口服。疗程 5-7 天,需完整疗程。",
    sideEffects: "常见:呕吐、腹泻;罕见:过敏反应(皮疹、面部水肿);长期使用致肠道菌群失调。",
    contraindications: "对青霉素过敏禁用;与氨基糖苷类合用需错开 2h;严重肾功能障碍调整剂量。",
    price: 22,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_antiinf_02",
    name: "头孢氨苄(Cefalexin / 头孢菌素)",
    category: "抗感染",
    symptoms: ["细菌感染", "皮肤", "泌尿道", "软组织"],
    description: "第一代头孢菌素,宠物常用抗生素。对革兰氏阳性菌和部分阴性菌有效,适用于皮肤脓皮症、泌尿道感染、软组织感染。",
    indications: ["浅表/深层脓皮症", "泌尿道感染", "软组织感染", "呼吸道感染"],
    dosage: "犬:10-22 mg/kg,每 8-12h 口服;猫:10-22 mg/kg,每 8-12h 口服。需完整疗程 7-14 天。",
    sideEffects: "常见:呕吐、腹泻(尤其空腹);罕见:过敏反应、嗜睡;长期使用致耐药。",
    contraindications: "对头孢类/青霉素过敏禁用;严重肾功能障碍减量;与氨基糖苷类合用增加肾毒性。",
    price: 28,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_antiinf_03",
    name: "速诺(Synulox / 阿莫西林克拉维酸钾)",
    category: "抗感染",
    symptoms: ["广谱抗生素", "皮肤", "呼吸道", "宠物专用"],
    description: "美国辉瑞(现 Zoetis)出品,阿莫西林+克拉维酸钾 4:1 复方。克拉维酸抑制β-内酰胺酶,扩大抗菌谱,覆盖产酶耐药菌。宠物专用品牌,适口性好。",
    indications: ["皮肤脓皮症", "呼吸道感染", "泌尿道感染", "牙周炎", "软组织感染"],
    dosage: "犬:12.5-25 mg/kg,每 8-12h 口服;猫:12.5 mg/kg,每 8-12h 口服。完整疗程 5-7 天。",
    sideEffects: "常见:呕吐、腹泻;罕见:过敏反应;长期使用致肠道菌群失调/耐药。",
    contraindications: "对青霉素/头孢过敏禁用;严重肾功能障碍减量;与氨基糖苷类合用需错开 2h。",
    price: 95,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_antiinf_04",
    name: "拜有利(Baytril / 恩诺沙星)",
    category: "抗感染",
    symptoms: ["氟喹诺酮", "深部感染", "泌尿道", "宠物专用"],
    description: "德国拜耳出品,恩诺沙星宠物专用注射液/片剂。氟喹诺酮类广谱抗生素,对革兰氏阴性菌、绿脓杆菌、支原体强力有效,适用于深部/难治性感染。",
    indications: ["深部脓皮症", "复杂泌尿道感染", "前列腺感染", "支原体感染", "绿脓杆菌感染"],
    dosage: "犬:5-20 mg/kg,每 24h 口服(片剂)或皮下注射;猫:5 mg/kg,每 24h(猫慎用,大剂量致视网膜毒性)。",
    sideEffects: "常见:胃肠道反应;罕见:幼年动物软骨损伤(<12 月龄)、猫视网膜变性(高剂量)、癫痫发作(中枢病史)。",
    contraindications: "8 月龄以下幼犬/12 周龄以下幼猫禁用(软骨);怀孕/哺乳期禁用;猫禁大剂量;癫痫病史慎用。",
    price: 145,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
];

// ===== 止痛(4 款)=====
const analgesic: Drug[] = [
  {
    id: "drug_pain_01",
    name: "美洛昔康(Meloxicam / Metacam)",
    category: "止痛",
    symptoms: ["止痛", "消炎", "骨关节炎", "NSAID"],
    description: "德国勃林格出品,选择性 COX-2 抑制剂,宠物一线 NSAID。强效止痛+消炎,适用于骨关节炎、术后疼痛、肌肉骨骼损伤。口服液/片剂,小型犬猫精确给药。",
    indications: ["骨关节炎慢性疼痛", "术后疼痛", "肌肉骨骼损伤", "退行性关节病"],
    dosage: "犬:首日 0.2 mg/kg,之后 0.1 mg/kg,每日 1 次口服/皮下;猫:0.1 mg/kg(单次)或 0.05 mg/kg 长期(限兽医指导,猫长期安全性有争议)。",
    sideEffects: "常见:胃肠道反应(呕吐、腹泻、食欲不振);罕见:肾损伤(尤其脱水)、肝毒性。",
    contraindications: "胃肠道溃疡/出血禁用;严重肾/肝功能障碍禁用;脱水/低血容量禁用;怀孕末期禁用;猫长期使用需谨慎。",
    price: 98,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_pain_02",
    name: "卡布洛芬(Carprofen / Rimadyl)",
    category: "止痛",
    symptoms: ["止痛", "骨关节炎", "犬专用", "NSAID"],
    description: "美国辉瑞(现 Zoetis)出品,犬专用 NSAID。选择性 COX-2 抑制剂,适用于犬骨关节炎慢性疼痛、术后疼痛控制。咀嚼片适口性好。",
    indications: ["犬骨关节炎", "术后疼痛", "髋关节发育不良(CHD)", "软组织损伤"],
    dosage: "犬:2 mg/kg,每日 2 次口服,或 4.4 mg/kg 每日 1 次(维持)。首剂可负荷。",
    sideEffects: "常见:食欲不振、呕吐、腹泻;罕见:肝毒性(尤其拉布拉多等品种)、肾损伤;特异质反应(不可预测的肝衰)。",
    contraindications: "猫禁用(毒性差异大);胃肠道溃疡禁用;严重肝/肾功能障碍禁用;怀孕动物禁用;6 周龄以下禁用。",
    price: 125,
    prescription: true,
    forSpecies: ["dog"],
  },
  {
    id: "drug_pain_03",
    name: "痛立定(Tolfedine / 托芬那酸)",
    category: "止痛",
    symptoms: ["止痛", "消炎", "退热", "NSAID"],
    description: "法国 Vetoquinol 出品,托芬那酸宠物专用 NSAID。适用于犬猫肌肉骨骼疼痛、术后疼痛控制、关节炎。比布洛芬选择性更高,胃肠道刺激较小。",
    indications: ["犬猫骨关节炎", "术后疼痛", "肌肉骨骼疼痛", "退热"],
    dosage: "犬:4 mg/kg,每日 1 次,皮下注射或口服,连用不超过 3 天;猫:4 mg/kg,每日 1 次,口服/皮下,连用不超过 3 天。",
    sideEffects: "常见:轻度呕吐、腹泻;罕见:胃溃疡、肾损伤(脱水时);注射部位短暂疼痛。",
    contraindications: "胃肠道溃疡/出血禁用;严重肾/肝功能障碍禁用;脱水禁用;怀孕末期禁用;不可与其他 NSAID 或糖皮质激素合用。",
    price: 88,
    prescription: true,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_pain_04",
    name: "安乃近(Metamizole / 氨基比林)",
    category: "止痛",
    symptoms: ["止痛", "退热", "解痉", "人药慎用"],
    description: "吡唑酮类解热镇痛药,强效退热+中等止痛+解痉作用。**人医已退出一线(可能致粒细胞缺乏),宠物仅作解热镇痛二线,需严格遵医嘱**。",
    indications: ["高热紧急退热(临时)", "内脏平滑肌痉挛性疼痛", "术后寒战"],
    dosage: "犬:20-50 mg/kg,每 8-12h 口服或肌肉注射;猫:**不推荐**(代谢差异大,易中毒)。",
    sideEffects: "严重:粒细胞缺乏(罕见但致命)、再生障碍性贫血;常见:低血压(注射过快)、过敏反应。",
    contraindications: "猫禁用;粒细胞减少史禁用;骨髓抑制禁用;严重肝/肾功能不全禁用;怀孕/哺乳禁用;不可长期使用(≤3 天)。",
    price: 10,
    prescription: true,
    forSpecies: ["dog"],
  },
];

// ===== 其他(2 款)=====
const others: Drug[] = [
  {
    id: "drug_other_01",
    name: "复合维生素 B 族(Vitamin B Complex)",
    category: "其他",
    symptoms: ["维生素补充", "食欲不振", "B 族缺乏"],
    description: "宠物用复合维生素 B 族补充剂,含 B1/B2/B6/B12/烟酸/泛酸等。适用于挑食/食欲不振/病后恢复/长期使用抗生素后 B 族流失补充。水溶性,过量一般不蓄积。",
    indications: ["挑食/食欲不振", "病后恢复", "长期抗生素后补充", "B 族缺乏症", "神经炎辅助"],
    dosage: "按体重:小型犬猫 1/2-1 片/日,中型犬 1-2 片/日,大型犬 2-3 片/日。餐后口服。",
    sideEffects: "水溶性维生素,罕见中毒;极高剂量偶见腹泻、尿黄(B2)。",
    contraindications: "已知对任何成分过敏禁用;不建议与左旋多巴合用(B6 拮抗);肾功能不全时大剂量 B 族可能蓄积。",
    price: 22,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
  {
    id: "drug_other_02",
    name: "鱼油(Fish Oil / Omega-3)",
    category: "其他",
    symptoms: ["美毛", "关节", "心血管", "omega-3"],
    description: "宠物用深海鱼油,富含 EPA+DHA omega-3 脂肪酸。适用于美毛/皮肤保养、骨关节炎辅助、心血管保健、肾病辅助。宠物用量高于人用(按 EPA+DHA 实际含量计算)。",
    indications: ["美毛/皮肤保养", "骨关节炎辅助", "心血管保健", "慢性肾病辅助", "认知功能(老年犬)"],
    dosage: "按 EPA+DHA 总和计算:犬 50-75 mg/kg/日,猫 30-50 mg/kg/日。餐时服用,与维生素 E 同补防氧化。",
    sideEffects: "常见:鱼腥味嗳气;罕见:软便(大剂量);长期高剂量可能影响血小板功能。",
    contraindications: "对鱼/海鲜过敏禁用;抗凝药治疗期慎用(高剂量 omega-3 抗凝);术前 2 周停用;鱼油变质(哈喇味)禁用。",
    price: 65,
    prescription: false,
    forSpecies: ["cat", "dog"],
  },
];

// ===== 合并 + 导出(48 → 52 款)=====
export const seedDrugsV040: Drug[] = [
  ...deworming,         // 8 款
  ...vaccines,          // 6 款
  ...digestive,         // 6 款
  ...skin,              // 6 款
  ...joint,             // 4 款
  ...heart,             // 4 款
  ...kidney,            // 4 款
  ...eyeEar,            // 4 款
  ...antiInfection,     // 4 款
  ...analgesic,         // 4 款
  ...others,            // 2 款
];

// ===== 工具:推广药清单(任务清单要求)=====
/** v0.4.0 推广药品 ID 清单(hard-code;运营/管理后台暂不开放编辑) */
export const PROMOTED_DRUG_IDS_V040: readonly string[] = [
  "drug_deworm_02",   // 拜耳拜宠清 (rank 90)
  "drug_deworm_03",   // 大宠爱 (rank 95)
  "drug_vaccine_01",  // 妙三多 (rank 100)
  "drug_digestive_01",// 宠物益生菌 (rank 80)
];
// 数量 = 4 款,在任务清单"3-5 款"区间内
